name: Metrics

on:
  schedule:
    # Runs daily at 00:00 PST (08:00 UTC). Note: shifts to 01:00 during PDT.
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PenneconDavid
          template: classic
          base: ""
          filename: metrics.plugin.isocalendar.fullyear.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  languages:
    needs: isocalendar
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PenneconDavid
          template: classic
          base: ""
          filename: metrics.plugin.languages.details.svg
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6
